server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  application:
    name: identity-service

  datasource:
    url: jdbc:postgresql://localhost:5432/identity_service
    username: postgres
    password: 1234567890
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
      format_sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
