server:
  port: 8888

app:
  api-prefix: /api/v1

services:
  user-service:
    url: http://localhost:8082/users
  listing-service:
    url: http://localhost:8081
  rating-service:
    url: http://localhost:8085

spring:
  application:
    name: api-gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/airbnb

  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            cors-configurations:
              '[/**]':
                allowed-origin-patterns:
                  - "http://localhost:5173"
                  - "http://localhost:3000"
                allowed-methods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowed-headers:
                  - "*"
                allow-credentials: true
                max-age: 3600

          routes:
            - id: profile_service
              uri: http://localhost:8082
              predicates:
                - Path=${app.api-prefix}/profile/**
              filters:
                - StripPrefix=3
                - PrefixPath=/users/profile
            - id: user_service
              uri: http://localhost:8082
              predicates:
                - Path=${app.api-prefix}/users/**
              filters:
                - StripPrefix=2
#                - PrefixPath=/users
            - id: listing_service
              uri: http://localhost:8081
              predicates:
                - Path=${app.api-prefix}/listings/**
              filters:
                - StripPrefix=2
            - id: rating_service
              uri: http://localhost:8085
              predicates:
                - Path=${app.api-prefix}/ratings/**
              filters:
                - StripPrefix=2
            - id: wishlist_service
              uri: http://localhost:8083
              predicates:
                - Path=${app.api-prefix}/wishlist/**
              filters:
                - StripPrefix=2
            - id: payment_service
              uri: http://localhost:8087
              predicates:
                - Path=${app.api-prefix}/payment-methods/**,${app.api-prefix}/transactions/**,${app.api-prefix}/refunds/**,${app.api-prefix}/payments/**
              filters:
                - StripPrefix=2
            - id: booking_service
              uri: http://localhost:8086
              predicates:
                - Path=${app.api-prefix}/bookings/**
              filters:
                - StripPrefix=2
