spring:
  application:
    name: rating-service

  datasource:
    url: jdbc:postgresql://ep-divine-math-a1lyqysl-pooler.ap-southeast-1.aws.neon.tech/listing_db?sslmode=require
    username: neondb_owner
    password: npg_GnXE70sJUjmu
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 300000
      max-lifetime: 900000
      connection-timeout: 20000
      keepalive-time: 300000


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        default_schema: public
        format_sql: false

server:
  port: 8085
