server:
  port: 8087
  servlet:
    context-path: /payments

spring:
  application:
    name: payment-service

  datasource:
    url: ${PAYMENT_DB_URL:jdbc:postgresql://ep-divine-math-a1lyqysl-pooler.ap-southeast-1.aws.neon.tech/payment_db?sslmode=require}
    username: ${PAYMENT_DB_USERNAME:neondb_owner}
    password: ${PAYMENT_DB_PASSWORD:npg_GnXE70sJUjmu}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 20000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  cache:
    type: ${CACHE_TYPE:simple}

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
    consumer:
      group-id: payment-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/airbnb}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:8080/realms/airbnb/protocol/openid-connect/certs}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

logging:
  level:
    root: INFO
    com.paymentservice: INFO

idp:
  url: ${IDP_URL:http://localhost:8080}
  client-id: ${PAYMENT_SERVICE_IDP_CLIENT_ID:payment_service}
  client-secret: ${PAYMENT_SERVICE_IDP_CLIENT_SECRET:by2n65zqJJrNemDHwVRSiOtl3f5CwdgK}

stripe:
  secret-key: ${STRIPE_SECRET_KEY:}
  webhook-secret: ${STRIPE_WEBHOOK_SECRET:}
  publishable-key: ${STRIPE_PUBLISHABLE_KEY:}

kafka:
  topics:
    payment-succeeded: payment.succeeded
    payout-completed: payout.completed
    refund-completed: refund.completed
    refund-failed: refund.failed
    notifications: notifications

payout:
  scheduler-delay-ms: ${PAYOUT_SCHEDULER_DELAY_MS:60000}

payment:
  reconciliation:
    enabled: ${PAYMENT_RECONCILIATION_ENABLED:false}
    delay-ms: ${PAYMENT_RECONCILIATION_DELAY_MS:3600000}
