UPDATE payments
SET status = CASE status
    WHEN 'CREATED' THEN 'PAYMENT_PENDING'
    WHEN 'SUCCEEDED' THEN 'PAID'
    WHEN 'FAILED' THEN 'PAYMENT_FAILED'
    WHEN 'CANCELLED' THEN 'PAYMENT_CANCELLED'
    WHEN 'PARTIALLY_REFUNDED' THEN 'PARTIALLY_REFUNDED'
    WHEN 'REFUNDED' THEN 'REFUNDED'
    ELSE COALESCE(status, 'PAYMENT_PENDING')
END
WHERE status IS NULL
   OR status IN ('CREATED', 'SUCCEEDED', 'FAILED', 'CANCELLED', 'PARTIALLY_REFUNDED', 'REFUNDED');

ALTER TABLE payments
    ALTER COLUMN status SET DEFAULT 'PAYMENT_PENDING';
