server:
  port: 8082
  servlet:
    context-path: /users

app:
  frontend-url: ${APP_FRONTEND_URL:http://localhost:3000}

spring:
  application:
    name: user-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/airbnb}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:8080/realms/airbnb/protocol/openid-connect/certs}

  datasource:
    url: ${USER_DB_URL:jdbc:postgresql://ep-divine-math-a1lyqysl-pooler.ap-southeast-1.aws.neon.tech/user_db?sslmode=require}
    username: ${USER_DB_USERNAME:neondb_owner}
    password: ${USER_DB_PASSWORD:npg_GnXE70sJUjmu}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 300000
      max-lifetime: 900000
      connection-timeout: 20000
      keepalive-time: 300000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

idp:
  url: ${IDP_URL:http://localhost:8080}
  client-id: ${USER_SERVICE_IDP_CLIENT_ID:user_service}
  client-secret: ${USER_SERVICE_IDP_CLIENT_SECRET:Vzg4aVN4v35o2HhDX0jsKcVX6mGN4c96}

services:
  listing-service:
    url: ${LISTING_SERVICE_URL:http://localhost:8081}
  rating-service:
    url: ${RATING_SERVICE_URL:http://localhost:8085}

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME:}
  api-key: ${CLOUDINARY_API_KEY:}
  api-secret: ${CLOUDINARY_API_SECRET:}

stripe:
  secret-key: ${STRIPE_SECRET_KEY:}
