server:
  port: 8082
  servlet:
    context-path: /users

app:
  frontend-url: http://localhost:3000

spring:
  application:
    name: user-service

  config:
    import:
      - optional:file:.env[.properties]
      - optional:file:user-service/.env[.properties]

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/airbnb

  datasource:
    url: jdbc:postgresql://ep-divine-math-a1lyqysl-pooler.ap-southeast-1.aws.neon.tech/user_db?sslmode=require
    username: neondb_owner
    password: npg_GnXE70sJUjmu
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 300000
      max-lifetime: 900000
      connection-timeout: 20000
      keepalive-time: 300000


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

idp:
  url: http://localhost:8080
  client-id: user_service
  client-secret: Vzg4aVN4v35o2HhDX0jsKcVX6mGN4c96

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME:}
  api-key: ${CLOUDINARY_API_KEY:}
  api-secret: ${CLOUDINARY_API_SECRET:}

# ===== STRIPE CONFIG =====
stripe:
  # Secret key - dùng test key khi develop
  secret-key: ${STRIPE_SECRET_KEY:}

  # Publishable key - dùng ở Frontend (an toàn để expose)
  publishable-key: ${STRIPE_PUBLISHABLE_KEY:}
